### ISSUE TITLE
ValueError: unconverted data remains: Z

### ISSUE THREAD

**Issue by dukemc1** [dillagr/pangaea-bingo-sentinel#1]
fmt = "%Y-%m-%dT%H:%M:%SZ" 

I have added Z at the end cause i have issues with the ValueError: unconverted data remains:Z

**Comment by dillagr** [comment]
when downloading the script, change line 29:

from:
    strtmstamp = time.strptime(tmstamp.split('+')[0], fmt)
to:
    strtmstamp = time.strptime(tmstamp.split('Z')[0], fmt)
